File "/home/tush/.conda/envs/airflow_env/1ib/python3.9/site-packages/pymysql/connections.py"”, line 725, in _read_packet
packet.raise_for_error()
File "/home/tush/.conda/envs/airflow_env/1lib/python3.9/site-packages/pymysql/protocol.py"”, line 221, in raise_for_error
err.raise_mysql_exception(self._data)
File "/home/tush/.conda/envs/airflow_env/1lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1067, [Rig¥el¥elNelygeV) RV IRVINE SoTVIoTeloyelYe Moy
[sqQL:
CREATE TABLE airflow.dataset (
id INTEGER NOT NULL AUTO_INCREMENT,
uri VARCHAR(3000) COLLATE latinl_general_cs NOT NULL,
extra JSON NOT NULL,
created_at TIMESTAMP(6) NOT NULL,
updated_at TIMESTAMP(6) NOT NULL,
CONSTRAINT dataset_pkey PRIMARY KEY (id)
D)

]
(Background on this error at: https://sqlalche.me/e/14/e398)
(airflow_env) [tush@syncdb@l airflow]$ I
